### ISSUE TITLE
constant retry to close process

### ISSUE THREAD

**Issue by cxmeel** [OrbitalOwen/roblox-win-installer-action#5]
A few days ago, I notice the action had started failing to run. There are a few warnings/errors output when the action runs, but after launching the Studio installer, the action states that it is going to terminate the process, and continues to do so indefinitely.

Here are two actions I've run recently:

*   https://github.com/ClockworkSquirrel/semver/actions/runs/797665703
*   (this one was set to continue on error) [https://github.com/ClockworkSquirrel/semver/actions/runs/804658407](https://github.com/ClockworkSquirrel/semver/actions/runs/804658407)

I've also re-run the action on a previously successful repo, and it failed there too.

**Comment by cxmeel** [comment]
[logs_4.zip](https://github.com/OrbitalOwen/roblox-win-installer-action/files/6411854/logs_4.zip)
[logs_11_continue_on_error.zip](https://github.com/OrbitalOwen/roblox-win-installer-action/files/6411855/logs_11_continue_on_error.zip)

**Comment by OrbitalOwen** [comment]
Sorry for the delay. This should be resolved by https://github.com/OrbitalOwen/roblox-win-installer/pull/11

Let me know if you are still having problems?
